# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1e72f460d4a26255bda9674769884e98e848732d5cd82b8821421dbd81d0a682355f5fd95b046175f1dc7326427f6ccd86f670968b2d79e9bc33024ca32fa4e

test:
  secret_key_base: 24979f4f1fa59bf01d4a63742d49ecc7255bff5e0c57da2fe3dc8ff0c85c911cd1e70701746ac0353ffeb0f7723087a791be0b8ba9097446626cd56ab87c714f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
